### ISSUE TITLE
Not sure how, but a Windows 11 update appears to have broken this?

### ISSUE THREAD

**Issue by Oxsynn** [Oxsynn/Win11CapsLockIndicator#1]
the image doesn't show up anymore in the taskbar, and running the application appears to cause the taskbar to freeze up, requiring a restart of windows explorer, without this app running.

Requires further testing.

**Comment by yukiloh** [comment]
It's true.I have a hearing impairment,I can't hear the capslock pressed on windows 11.
I really like the icon that appears when you press the capslock on windows 10.

**Comment by Oxsynn** [comment]
I've found that this issue seems to have stop happening after a windows update.  Will monitor, but this has tentatively been resolved.
